#!/bin/bash

set -e

. ../common

# Go
install_packages go

# My text editor of choice
install_packages neovim python-pip

# Deoplete dependencies
runuser -l arnar -c "pip3 install --user pynvim"

# Pre-load vim-go dependencies
# PlugInstall freezes otherwise :/
runuser -l arnar -c "go get github.com/zmb3/gogetdoc"
runuser -l arnar -c "go get golang.org/x/tools/cmd/guru"
runuser -l arnar -c "go get golang.org/x/tools/gopls"
runuser -l arnar -c "go get github.com/davidrjenni/reftools/cmd/fillstruct"
runuser -l arnar -c "go get github.com/rogpeppe/godef"
runuser -l arnar -c "go get github.com/fatih/motion"
runuser -l arnar -c "go get github.com/kisielk/errcheck"
runuser -l arnar -c "go get github.com/go-delve/delve/cmd/dlv"
runuser -l arnar -c "go get github.com/mdempsky/gocode"
runuser -l arnar -c "go get github.com/josharian/impl"
runuser -l arnar -c "go get github.com/golangci/golangci-lint/cmd/golangci-lint"
runuser -l arnar -c "go get github.com/jstemmer/gotags"
runuser -l arnar -c "go get golang.org/x/tools/cmd/gorename"
runuser -l arnar -c "go get golang.org/x/tools/cmd/goimports"
runuser -l arnar -c "go get github.com/stamblerre/gocode"
runuser -l arnar -c "go get github.com/fatih/gomodifytags"
runuser -l arnar -c "go get honnef.co/go/tools/cmd/keyify"
runuser -l arnar -c "go get golang.org/x/lint/golint"
runuser -l arnar -c "go get github.com/koron/iferr"
runuser -l arnar -c "go get github.com/klauspost/asmfmt/cmd/asmfmt"

# NeoVim
runuser -l arnar -c "curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
runuser -l arnar -P -c "nvim +PlugInstall +qall --headless"
install_packages the_silver_searcher
ln -s /usr/bin/nvim /usr/bin/vim

# Misc tools
install_packages curl jq kr
