sudo: required

jobs:
  include:
    - stage: update aurnar
      services: docker
      before_install:
      - docker build -t aurnar-sync .
      script:
      - docker run -e "B2_ACCOUNT_ID=$B2_ACCOUNT_ID" -e "B2_ACCOUNT_KEY=$B2_ACCOUNT_KEY" aurnar-sync
    - stage: build
      addons:
        apt:
          packages:
            - libseccomp-dev
      before_install:
      - sudo apt-get -y install curl gnupg software-properties-common
      - wget -O- -q https://github.com/containerd/containerd/releases/download/v1.2.0/containerd-1.2.0.linux-amd64.tar.gz | sudo tar xpz -C /
      - sudo wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 -O /bin/runc && sudo chmod +x /bin/runc
      - curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | sudo DARCH_TAG=v0.27.0 bash /dev/stdin
      - sudo containerd &
      - darch version
      - sudo ctr version
      - sudo runc --version
      - sudo darch images pull godarch/arch:latest
      script:
      - "./ci"


