#!/bin/bash
set -e

. ./build

IMAGE="workstation"

sudo darch images push --user $DOCKER_LOGIN_USERNAME:$DOCKER_LOGIN_PASSWORD granra/darch-arch-$IMAGE:$TAG
sudo darch images push --user $DOCKER_LOGIN_USERNAME:$DOCKER_LOGIN_PASSWORD granra/darch-arch-$IMAGE:latest
