#!/bin/bash

set -e

. ../common

# Install graphics driver
install_packages xf86-video-amdgpu

# Enable systemd networking.
cp wired.network /etc/systemd/network/
systemctl enable systemd-networkd

# Insert my firewall rules
cp iptables.rules /etc/iptables/iptables.rules
systemctl enable iptables

# Tool to control RGB lights on my PC
install_packages msi-rgb

# My workstation requires special kernel parameters
cp darch-extract /darch-extract

# Install update script
cp darch-update /usr/local/bin/darch-update

clear_package_cache
