#!/bin/bash

set -e

. ../common

# Install graphics driver
install_packages xf86-video-amdgpu

# Enable systemd networking.
cp wired.network /etc/systemd/network/
systemctl enable systemd-networkd
systemctl enable systemd-resolved

# Tool to control RGB lights on my PC
install_packages msi-rgb

# My workstation requires special kernel parameters
cp darch-extract /darch-extract

clear_package_cache