#!/bin/bash
set -e

. ../common

# Switch to unstable
pacman-mirrors --api -S unstable

# Now update everything.
pacman -Syyu --noconfirm

# Run base install, with dev tools. The "bootstrap" fs doesn't contain everything, just what you need to bootstrap.
install_packages base base-devel

# Packages that were removed from the base group when it was changed to a metapackage
install_packages linux-firmware lvm2 e2fsprogs device-mapper dhcpcd diffutils inetutils less man-db man-pages sysfsutils usbutils which

# Install Kernel
install_packages linux53

# Add /etc/hosts
cp hosts /etc/hosts

# Timezone
rm -f /etc/localtime
ln -s ../usr/share/zoneinfo/America/New_York /etc/localtime

# Time sync
install_packages ntp
systemctl enable ntpd

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Install Darch
install_packages darch
# We don't need grub as a bootloader, but we use
# their helper scripts in Darch to generate menu entries.
install_packages grub
# Enable containerd, which was brought in as a dependency.
systemctl enable containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
mkdir -p /etc/containerd
echo "root = \"/var/lib/darch/containerd\"" > /etc/containerd/config.toml

# Install extra tools
install_packages iptables bind-tools openssh rsync screen
