#!/bin/bash
set -e

. ../common

# Install zsh
install_packages zsh fzf

# Add users
useradd -m -G adm,ftp,games,video,http,log,rfkill,sys,systemd-journal,users,uucp,wheel -s /usr/bin/zsh arnar

# Set the user password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd arnar
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd arnar
fi

# Install fresh copy of dotfiles for arnar.
# dotbot requires Python.
install_packages python git
runuser -l arnar -c "git clone https://github.com/arnarg/dotfiles.git ~/.dotfiles"
runuser -l arnar -c "cd ~/.dotfiles && ./install"
# Now that they are installed, removed dotbot to clean up the image.
runuser -l arnar -c "rm -r ~/.dotfiles/dotbot"

# Install zsh plugins
runuser -l arnar -c "mkdir -p ~/.config/zsh/plugins"
runuser -l arnar -c "git clone --single-branch -b v1.10.3 https://github.com/sindresorhus/pure.git ~/.config/zsh/plugins/pure"
# One symlink in pure doesn't persist when I git pull for some reason
runuser -l arnar -c "ln -s async.zsh ~/.config/zsh/plugins/pure/async"

# Setup sudo
install_packages sudo
echo "arnar ALL=(ALL) ALL" >> /etc/sudoers.d/arnar
# Don't lecture me sudo!
echo "Defaults lecture = never" >> /etc/sudoers.d/lecture

# Create base directories
mkdir -p /home/arnar/Downloads
mkdir -p /home/arnar/Pictures
mkdir -p /home/arnar/Code

# Insert ~/.profile
cp profile /home/arnar/.profile

# Download and set wallpaper
wget https://i.imgur.com/kiy2C51.jpg -O /home/arnar/Pictures/wallpaper.jpg || true # let's not fail build if the picture doesn't exist
cp fehbg /home/arnar/.fehbg

# I have some dotfiles in home folder that I would like to persist
ln -s /home/arnar/.persist/gitconfig /home/arnar/.gitconfig
ln -s /home/arnar/.persist/b2_account_info /home/arnar/.b2_account_info

# Make sure arnar owns everything in /home/arnar
chown -R arnar:arnar /home/arnar
