#!/bin/bash
set -e

. ../common


# Install X
install_packages xorg-server xorg-xinit xorg-setxkbmap xorg-xsetroot

# WM and X, Font awesome for icons in i3 status bar
install_packages i3-gaps i3blocks rofi j4-dmenu-desktop ttf-font-awesome

# My terminal of choice
install_packages rxvt-unicode ttf-inconsolata

# My browser of choice
install_packages firefox

# My music player of choice
install_packages spotify

# I use pulseaudio
install_packages pulseaudio