#!/bin/bash
set -e

. ../common

# Install sway
install_packages sway swayidle xorg-server-xwayland dmenu bemenu-git waybar

# My terminal of choice
install_packages alacritty

# Install fonts
install_packages ttf-inconsolata ttf-inconsolata-lgc-for-powerline ttf-roboto ttf-font-icons

# My browser of choice
install_packages firefox

# My music player of choice
install_packages spotify

# I use pulseaudio
install_packages pulseaudio
