#!/bin/bash
set -e

. ../common

# Drivers
install_packages xf86-video-amdgpu

# WM and X, Font awesome for icons in i3 status bar
install_packages i3-gaps i3blocks j4-dmenu-desktop xorg-xinit xorg-setxkbmap ttf-font-awesome

# My terminal of choice
install_packages rxvt-unicode ttf-inconsolata

# My browser of choice
install_packages firefox

# My music player of choice
install_packages spotify

# I use pulseaudio
install_packages pulseaudio

clear_package_cache